php84-debian12:
  - 'php84-debian12/**'
  - 'Dockerfile'

php84-debian11:
  - 'php84-debian11/**'
  - 'Dockerfile'

php83-debian12:
  - 'php83-debian12/**'
  - 'Dockerfile'

php83-debian11:
  - 'php83-debian11/**'
  - 'Dockerfile'

php82-debian12:
  - 'php82-debian12/**'
  - 'Dockerfile'

php82-debian11:
  - 'php82-debian11/**'
  - 'Dockerfile'

php81-debian12:
  - 'php81-debian12/**'
  - 'Dockerfile'

php81-debian11:
  - 'php81-debian11/**'
  - 'Dockerfile'
