name: Build

on:
    push:

jobs:
    changes:
      name: Detect Changes
      runs-on: ubuntu-latest
      outputs:
        variants: ${{ steps.filter.outputs.changes }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: ${{ startsWith(github.ref, 'refs/tags/v') && '0' || '1' }}

        - name: Retrieve the previous release version
          if: startsWith(github.ref, 'refs/tags/v')
          id: previous_release
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            # Attempt to get the tag of the second-to-last release
            PREVIOUS_TAG=$(gh release list --limit 2 --json tagName | jq -r '. | select(length > 1) | .[1].tagName')

            if [[ -z "$PREVIOUS_TAG" ]]; then
              echo "No previous release found. Falling back to the first commit."
              REF=$(git rev-list --max-parents=0 HEAD)
            else
              echo "Found previous release: $PREVIOUS_TAG"
              REF=$PREVIOUS_TAG
            fi

            echo "The reference point is: $REF"
            echo "ref=$REF" >> $GITHUB_OUTPUT

        - uses: dorny/paths-filter@v3
          id: filter
          with:
            filters: .github/filters.yml
            base: ${{ startsWith(github.ref, 'refs/tags/v') && steps.previous_release.outputs.ref || '' }}

    build:
        needs: changes
        name: Build ${{ matrix.variant }} image
        runs-on: ubuntu-latest
        if: needs.changes.outputs.variants != '[]'
        concurrency:
          group: build-${{ matrix.variant }}
          cancel-in-progress: true
        strategy:
          fail-fast: false
          matrix:
            variant: ${{ fromJson(needs.changes.outputs.variants) }}
        permissions:
          contents: read
          packages: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Expose environment variables for caching Docker build
              uses: actions/github-script@v7
              with:
                script: |
                  core.exportVariable('ACTIONS_RESULTS_URL', process.env['ACTIONS_RESULTS_URL'])
                  core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN'])

            - name: Get composer cache directory
              id: composer-cache
              working-directory: ./tests
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                path: ${{ steps.composer-cache.outputs.dir }}
                key: ${{ runner.os }}-composer-${{ hashFiles('tests/composer.lock') }}
                restore-keys: ${{ runner.os }}-composer-

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.4'

            - name: Build
              env:
                DOCKER_BUILD_EXTRA: >-
                  --cache-from type=gha,url_v2=${{ env.ACTIONS_RESULTS_URL }},token=${{ env.ACTIONS_RUNTIME_TOKEN }},scope=${{ matrix.variant }}
                  --cache-to type=gha,url_v2=${{ env.ACTIONS_RESULTS_URL }},token=${{ env.ACTIONS_RUNTIME_TOKEN }},scope=${{ matrix.variant }},mode=max,repository=${{ github.repository }}
              run: make build-${{ matrix.variant }}

            - name: Test
              run: make test-setup test-${{ matrix.variant }}

            - name: Login to GitHub Container Registry
              if: startsWith(github.ref, 'refs/tags/v')
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Push to GitHub Container Registry
              if: startsWith(github.ref, 'refs/tags/v')
              run: make push-${{ matrix.variant }}
