name: Build PHP 8.4 on Debian 12

on:
    push:
        paths:
            - 'php84-debian12/**'
            - 'custom-debian12-builder/**'
            - '.github/workflows/build.yml'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Get composer cache directory
              id: composer-cache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                path: ${{ steps.composer-cache.outputs.dir }}
                key: ${{ runner.os }}-composer-${{ hashFiles('tests/composer.lock') }}
                restore-keys: ${{ runner.os }}-composer-

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.4'

            - name: Build
              run: make build-php84-debian12

            - name: Test
              run: make test-setup test-php84-debian12
